### ISSUE TITLE
Instalando "Python3" no linux

### ISSUE THREAD

**Issue by diraol** [rgaiacs/2015-09-10-usp#2]
Será que não vale, antes de explicar como instalar e/ou sugerir a instalação do "Anaconda" sugerir que as pessoas testem se já tem python3?

Hoje em dia já vem instalado por padrão em (quase) todas as distros (todas que eu testei pelo menos).

**Comment by rgaiacs** [comment]
> Será que não vale, antes de explicar como instalar e/ou sugerir a instalação do "Anaconda" sugerir que as pessoas testem se já tem python3?

A sugestão de instalar o Anaconda é para evitar dos participantes terem problemas ao instalar o IPython, NumPy, SciPy, matplotlib, ... Assim todo mundo fica com um ambiente padronizado o que facilita problemas.

Participantes familiarizados com alguma distribuição de GNU/Linux não precisam instalar o Anaconda desde que saibam instalar IPython, NumPy, SciPy, matplotlib, ... pelo gerenciador de pacotes.

**Comment by diraol** [comment]
blz. =)

Valeu pela explicação!
